function dispPrice() {
    // will display heatmap generated by d3 using housing prices scaled to budget
    alert("https://www.quandl.com/data/ZILLOW-Zillow-Real-Estate-Research?keyword=ny")
}

function getData(name, dataUrL) {
    $.ajax({ 
        type : "GET", 
        url : dataUrl,
        success : function(result) { 
            console.log(name, result);
        }, 
        error : function(result) { 
            //handle the error 
        } 
    });
}